<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="process" nsURI="ecore://nasdanika.org/models/process" nsPrefix="org.nasdanika.models.process">
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedStringIdentity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumers" upperBound="-1"
        eType="#//ResourceConsumer" eOpposite="#//ResourceConsumer/resources"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceConsumer" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedStringIdentity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" eOpposite="#//Resource/consumers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//ResourceConsumer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/actors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//ResourceConsumer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" eOpposite="#//Actor/roles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessElement">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.graph.model/model/graph.ecore#//ConnectionTarget">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.graph.model/model/graph.ecore#//Connection">
        <eTypeArguments eClassifier="#//ProcessElement"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.models.party/model/party.ecore#//Role"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/activities"/>
    <eGenericSuperTypes eClassifier="#//ResourceConsumer"/>
    <eGenericSuperTypes eClassifier="#//ProcessElement"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.graph.model/model/graph.ecore#//Node">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.graph.model/model/graph.ecore#//Connection">
        <eTypeArguments eClassifier="#//ProcessElement"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedStringIdentity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" eOpposite="#//Activity/artifacts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositories" upperBound="-1"
        eType="#//Repository" eOpposite="#//Repository/artifacts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/outputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" upperBound="-1"
        eType="#//Call" eOpposite="#//Call/request"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" upperBound="-1"
        eType="#//Call" eOpposite="#//Call/response"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/repositories"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Human" eSuperTypes="#//Actor ../../org.nasdanika.models.party/model/party.ecore#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eGenericSuperTypes eClassifier="#//Activity"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//Catalog"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.graph.model/model/graph.ecore#//CompositeNode">
      <eTypeArguments eClassifier="#//ProcessElement"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.graph.model/model/graph.ecore#//Connection">
        <eTypeArguments eClassifier="#//ProcessElement"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/transitions"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.graph.model/model/graph.ecore#//Connection">
      <eTypeArguments eClassifier="#//ProcessElement"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call">
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/requests"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/responses"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.graph.model/model/graph.ecore#//Connection">
      <eTypeArguments eClassifier="#//ProcessElement"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
